version: '3.4'
services:

  api:
    image: phylocko/flapmyport_api:0.1.0
    container_name: api
    ports:
      - "8080:8080"
    environment:
      - LISTEN_PORT=8080     
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASSWORD=${DBPASSWORD}
      - DBHOST=db
    depends_on:
      - db
 
  snmpflapd:
    image: phylocko/snmpflapd:1.0.0
    container_name: snmpflapd
    ports: 
      - "${LISTEN_PORT}:${LISTEN_PORT}"
    environment:
      - LOGFILE=${LOGFILE}
      - LISTEN_ADDRESS=${LISTEN_ADDRESS}
      - LISTEN_PORT=${LISTEN_PORT}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASSWORD=${DBPASSWORD}
      - DBHOST=db
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql
    volumes:
      - fmp-mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASSWORD}
    # uncomment for accessing mysql from outside
    # ports:
    #   - "3306:3306"
    #   - "33060:33060"
  
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx
      - ./web:/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api

volumes:
  fmp-mysql-data:
    driver: local
